# Generated by Django 3.2 on 2022-01-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_joke_joke_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='name',
            new_name='setup',
        ),
    ]
